load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "get",
    srcs = ["get.go"],
    importpath = "github.com/ajmcquilkin/mini-lambda/cmd/mini-lambda/function/get",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/api",
        "//internal/client",
        "@com_github_spf13_cobra//:cobra",
    ],
)
