load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "schedulermock",
    srcs = ["mock_scheduler.go"],
    importpath = "github.com/ajmcquilkin/mini-lambda/internal/scheduler/schedulermock",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/model",
        "@org_uber_go_mock//gomock",
    ],
)
