// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ajmcquilkin/mini-lambda/internal/scheduler (interfaces: Scheduler)
//
// Generated by this command:
//
//	mockgen -destination=schedulermock/mock_scheduler.go -package=schedulermock github.com/ajmcquilkin/mini-lambda/internal/scheduler Scheduler
//

// Package schedulermock is a generated GoMock package.
package schedulermock

import (
	context "context"
	reflect "reflect"

	model "github.com/ajmcquilkin/mini-lambda/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
	isgomock struct{}
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockScheduler) Invoke(ctx context.Context, fnName string, payload []byte) (*model.InvokeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, fnName, payload)
	ret0, _ := ret[0].(*model.InvokeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockSchedulerMockRecorder) Invoke(ctx, fnName, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockScheduler)(nil).Invoke), ctx, fnName, payload)
}

// Shutdown mocks base method.
func (m *MockScheduler) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockSchedulerMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockScheduler)(nil).Shutdown), ctx)
}
