// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ajmcquilkin/mini-lambda/internal/store (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=storemock/mock_store.go -package=storemock github.com/ajmcquilkin/mini-lambda/internal/store Store
//

// Package storemock is a generated GoMock package.
package storemock

import (
	context "context"
	reflect "reflect"

	model "github.com/ajmcquilkin/mini-lambda/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}

// CreateFunction mocks base method.
func (m *MockStore) CreateFunction(ctx context.Context, fn *model.Function) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFunction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFunction indicates an expected call of CreateFunction.
func (mr *MockStoreMockRecorder) CreateFunction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFunction", reflect.TypeOf((*MockStore)(nil).CreateFunction), ctx, fn)
}

// DeleteFunction mocks base method.
func (m *MockStore) DeleteFunction(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFunction", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFunction indicates an expected call of DeleteFunction.
func (mr *MockStoreMockRecorder) DeleteFunction(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFunction", reflect.TypeOf((*MockStore)(nil).DeleteFunction), ctx, name)
}

// GetFunction mocks base method.
func (m *MockStore) GetFunction(ctx context.Context, name string) (*model.Function, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunction", ctx, name)
	ret0, _ := ret[0].(*model.Function)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunction indicates an expected call of GetFunction.
func (mr *MockStoreMockRecorder) GetFunction(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunction", reflect.TypeOf((*MockStore)(nil).GetFunction), ctx, name)
}

// ListFunctions mocks base method.
func (m *MockStore) ListFunctions(ctx context.Context) ([]*model.Function, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFunctions", ctx)
	ret0, _ := ret[0].([]*model.Function)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFunctions indicates an expected call of ListFunctions.
func (mr *MockStoreMockRecorder) ListFunctions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFunctions", reflect.TypeOf((*MockStore)(nil).ListFunctions), ctx)
}

// Migrate mocks base method.
func (m *MockStore) Migrate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockStoreMockRecorder) Migrate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockStore)(nil).Migrate), ctx)
}

// UpdateFunctionConfiguration mocks base method.
func (m *MockStore) UpdateFunctionConfiguration(ctx context.Context, fn *model.Function) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFunctionConfiguration", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFunctionConfiguration indicates an expected call of UpdateFunctionConfiguration.
func (mr *MockStoreMockRecorder) UpdateFunctionConfiguration(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFunctionConfiguration", reflect.TypeOf((*MockStore)(nil).UpdateFunctionConfiguration), ctx, fn)
}
