load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "invoke",
    srcs = ["invoke.go"],
    importpath = "github.com/ajmcquilkin/mini-lambda/cmd/mini-lambda/function/invoke",
    visibility = ["//visibility:public"],
    deps = [
        "//cmd/mini-lambda/internal/cli",
        "//internal/client",
        "@com_github_spf13_cobra//:cobra",
    ],
)
