load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "store",
    srcs = [
        "sqlite.go",
        "store.go",
    ],
    embedsrcs = [
        "migrations/0001_init.down.sql",
        "migrations/0001_init.up.sql",
        "migrations/0002_drop_last_invoked_at.down.sql",
        "migrations/0002_drop_last_invoked_at.up.sql",
    ],
    importpath = "github.com/ajmcquilkin/mini-lambda/internal/store",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/model",
        "@com_github_golang_migrate_migrate_v4//:migrate",
        "@com_github_golang_migrate_migrate_v4//database/sqlite",
        "@com_github_golang_migrate_migrate_v4//source/iofs",
        "@org_modernc_sqlite//:sqlite",
        "@org_modernc_sqlite//lib",
    ],
)

go_test(
    name = "store_test",
    srcs = ["sqlite_test.go"],
    embed = [":store"],
    deps = [
        "//internal/model",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
