load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "serve",
    srcs = ["serve.go"],
    importpath = "github.com/ajmcquilkin/mini-lambda/cmd/mini-lambda/serve",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_viper//:viper",
    ],
)
