load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "daemon",
    srcs = ["daemon.go"],
    importpath = "github.com/ajmcquilkin/mini-lambda/internal/daemon",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/api",
        "//internal/apierror",
        "//internal/model",
        "//internal/runtime",
        "//internal/runtime/docker",
        "//internal/runtimeapi",
        "//internal/scheduler",
        "//internal/store",
    ],
)

go_test(
    name = "daemon_test",
    srcs = ["daemon_test.go"],
    embed = [":daemon"],
    deps = [
        "//internal/model",
        "//internal/store",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
